name: continuous integration
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          source $VENV
          make tests
